#!/bin/bash

# DKIM config
dkimConfig()
{
    postconf -e milter_protocol=2
    postconf -e milter_default_action=accept
    postconf -e smtpd_milters=inet:localhost:12301

    rm -f /etc/opendkim/KeyTable
    rm -f /etc/opendkim/SigningTable

    echo "DNS records:"
    for d in $OPENDKIM_DOMAINS ; do
      domain=$(echo "$d"| cut -f1 -d '=')
      selector=$(expr match "$d" '.*\=\(.*\)')
      if [ -z "$selector" ] ; then
        selector="mail"
      fi

      domainDir="/etc/opendkim/keys/$domain"
      privateFile="$domainDir/$selector.private"
      txtFile="$domainDir/$selector.txt"
      if [ ! -f "$privateFile" ] ; then
        echo "No DKIM private key found for selector '$selector' in domain '$domain'. Generating one now..."
        mkdir -p "$domainDir"
        opendkim-genkey -D "$domainDir" --selector=$selector --domain=$domain --append-domain
      fi

      # Ensure strict permissions required by opendkim
      chown opendkim:opendkim "$domainDir" "$privateFile"
      chmod a=,u=rw "$privateFile"

      echo "$selector._domainkey.$domain $domain:$selector:$privateFile" >> /etc/opendkim/KeyTable
      echo "*@$domain $selector._domainkey.$domain" >> /etc/opendkim/SigningTable
      
      cat "$txtFile"
    done
}

# Unclean container stop might leave pid files around and rsyslogd seems
# sometimes falsely think it's already running if some other process
# happens to have its old pid when starting.
rm -f \
  /run/opendkim.pid \
  /run/rsyslogd.pid \
  /var/spool/postfix/pid/master.pid

sed -i -e '17s|^#||' -e '18s|^#||' -e '22s|^#||' -e '28s|^#||' /etc/postfix/master.cf

# POSTFIX_var env -> postconf -e var=$POSTFIX_var
for e in ${!POSTFIX_*} ; do postconf -e "${e:8}=${!e}" ; done
chown -R postfix:postfix /var/lib/postfix /var/mail /var/spool/postfix
chown root /var/spool/postfix
chown root /var/spool/postfix/pid
chown -R :postdrop /var/spool/postfix/public
chown -R :postdrop /var/spool/postfix/maildrop

# OPENDKIM_var env -> put "key value" line in /etc/opendkim.conf
echo -n > /etc/opendkim.conf
for e in ${!OPENDKIM_*} ; do
  if [ "$e" == "OPENDKIM_DOMAINS" ] ; then
    continue
  fi
  echo "${e:9} ${!e}" >> /etc/opendkim.conf
done

trap "/usr/sbin/postfix stop; pkill -TERM opendkim; pkill -TERM rsyslogd" SIGTERM SIGINT

rsyslogd
if [ ! -z "$OPENDKIM_DOMAINS" ] ; then
  dkimConfig
  /usr/sbin/opendkim -u opendkim -P /run/opendkim.pid -x /etc/opendkim.conf
fi
/usr/sbin/postfix start
#wait $(cat /var/spool/postfix/pid/master.pid) $(cat /run/opendkim.pid)
sleep 10
while [ -e /var/spool/postfix/pid/master.pid ] && [ -e /run/opendkim.pid ]; do
  if [ ! -d /proc/$(tr -d " \t" < /var/spool/postfix/pid/master.pid) ]; then
    exit 1
  fi
  if [ ! -d /proc/$(tr -d " \t" < /run/opendkim.pid) ]; then
    exit 1
  fi
  sleep 10
done
exit 0
