#!/bin/bash

# DKIM config
dkimConfig()
{
    postconf -e milter_default_action=accept
    postconf -e smtpd_milters=inet:localhost:12301

    rm -f /etc/opendkim/KeyTable
    rm -f /etc/opendkim/SigningTable

    echo "DNS records:"
    for d in $OPENDKIM_DOMAINS ; do
      domain=$(echo "$d"| cut -f1 -d '=')
      selector=$(expr match "$d" '.*\=\(.*\)')
      if [ -z "$selector" ] ; then
        selector="mail"
      fi

      domainDir="/etc/opendkim/keys/$domain"
      privateFile="$domainDir/$selector.private"
      txtFile="$domainDir/$selector.txt"
      if [ ! -f "$privateFile" ] ; then
        echo "No DKIM private key found for selector '$selector' in domain '$domain'. Generating one now..."
        mkdir -p "$domainDir"
        opendkim-genkey -D "$domainDir" --selector=$selector --domain=$domain --append-domain
      fi

      # Ensure strict permissions required by opendkim
      chown opendkim:opendkim "$domainDir" "$privateFile"
      chmod a=,u=rw "$privateFile"

      echo "$selector._domainkey.$domain $domain:$selector:$privateFile" >> /etc/opendkim/KeyTable
      echo "*@$domain $selector._domainkey.$domain" >> /etc/opendkim/SigningTable

      cat "$txtFile"
    done
}

# Unclean container stop might leave pid files around and rsyslogd seems
# sometimes falsely think it's already running if some other process
# happens to have its old pid when starting.
rm -f \
  /run/opendkim.pid \
  /run/rsyslogd.pid \
  /var/spool/postfix/pid/master.pid

TLS_CERT="${TLS_CERT:-/etc/tls/tls.crt}"
TLS=""
if [ -e "$TLS_CERT" ]; then
  TLS=$(sha1sum $TLS_CERT)
fi

if [ ! -z "$SUBMISSION" ]; then
  sed -i -re 's|^#submission|submission|' -re 's/^#  -o(.*)(smtpd_reject_unlisted|submission|wrappermode|ORIGINATING)/  -o\1\2/' -re 's/^#  -o smtpd_(client|helo|sender|relay|recipient)_restrictions=.*/  -o smtpd_\1_restrictions=\$mua_\1_restrictions/' /etc/postfix/master.cf
  if [ "$SUBMISSION" == "auth" ]; then
    sed -i -re 's/^#  -o smtpd_(sasl|tls)_/  -o smtpd_\1_/' /etc/postfix/master.cf
  fi
fi

# POSTFIX_var env -> postconf -e var=$POSTFIX_var
for e in ${!POSTFIX_*} ; do postconf -e "${e:8}=${!e}" ; done
# POSTFIXMASTER_var env -> postconf -Me var=$POSTFIXMASTER_var + replace __ with /
for e in ${!POSTFIXMASTER_*} ; do v="${e:14}" && postconf -Me "${v/__/\/}=${!e}"; done
# POSTMAP_var env value -> /etc/postfix/var
for e in ${!POSTMAP_*} ; do echo "${!e}" > "/etc/postfix/${e:8}" && postmap "/etc/postfix/${e:8}"; done

chown -R postfix:postfix /var/lib/postfix /var/mail /var/spool/postfix
chown root /var/spool/postfix
chown root /var/spool/postfix/pid
chown -R :postdrop /var/spool/postfix/public
chown -R :postdrop /var/spool/postfix/maildrop
newaliases
if [ -d /etc/postfix/maps ]; then
  pushd /etc/postfix/maps
  for map in *; do
    if [ "$map" = "*" ]; then
      continue
    fi
    if [[ "$map" == *.db ]]; then
      continue
    fi
    postmap $map
  done
  popd
fi

# OPENDKIM_var env -> put "key value" line in /etc/opendkim.conf
echo -n > /etc/opendkim.conf
for e in ${!OPENDKIM_*} ; do
  if [ "$e" == "OPENDKIM_DOMAINS" ] ; then
    continue
  fi
  echo "${e:9} ${!e}" >> /etc/opendkim.conf
done

trap "/usr/sbin/postfix stop; pkill -TERM opendkim; pkill -TERM rsyslogd" SIGTERM SIGINT

if [ -e /etc/rsyslog.conf ]; then
  echo "Skipping /etc/rsyslog.conf generating - file already exists"
else
  cat <<'EOF' > /etc/rsyslog.conf
$ModLoad imuxsock
$WorkDirectory /var/spool/rsyslog
include(file="/etc/rsyslog.d/*.conf")
*.*;auth,authpriv.none /dev/stdout
EOF

  if [ "${RSYSLOG_TIMESTAMP}" == 'no' ] ; then
    echo '$template noTimestampFormat,"%syslogtag%%msg%\n"' >> /etc/rsyslog.conf
    echo '$ActionFileDefaultTemplate noTimestampFormat' >> /etc/rsyslog.conf
  fi

  if [ "${RSYSLOG_LOG_TO_FILE}" == 'yes' ] ; then
    echo 'mail.* -/var/log/mail.log' >> /etc/rsyslog.conf
  fi

  if [ -z ${RSYSLOG_REMOTE_PORT} ] ; then
    RSYSLOG_REMOTE_PORT=514
  fi
  if [ -z ${RSYSLOG_REMOTE_TEMPLATE} ] ; then
    RSYSLOG_REMOTE_TEMPLATE=RSYSLOG_ForwardFormat
  fi
  if [ ! -z ${RSYSLOG_REMOTE_HOST} ] ; then
    echo "*.* action(type=\"omfwd\" target=\"${RSYSLOG_REMOTE_HOST}\" port=\"${RSYSLOG_REMOTE_PORT}\" template=\"${RSYSLOG_REMOTE_TEMPLATE}\")" >> /etc/rsyslog.conf
  fi
fi
if [ ! -e /dev/log ]; then
  rsyslogd -n &
fi
if [ ! -z "$OPENDKIM_DOMAINS" ] ; then
  dkimConfig
  /usr/sbin/opendkim -u opendkim -P /run/opendkim.pid -x /etc/opendkim.conf
else
  ln -s /var/spool/postfix/pid/master.pid /run/opendkim.pid
fi
if [ ! -z "$POSTSRSD_DOMAIN" ] ; then
  postsrs="-f10001 -r10002 -s/etc/postfix/postsrsd.secret -d${POSTSRSD_DOMAIN} -unobody"
  if [ ! -z "$POSTSRSD_EXCLUDE" ] ; then
    postsrs="${postsrs} -X${POSTSRSD_EXCLUDE}"
  fi
  if [ ! -z "$POSTSRSD_SECRET" ] ; then
    echo "$POSTSRSD_SECRET" > /etc/postfix/postsrsd.secret
  fi
  if [ ! -e "/etc/postfix/postsrsd.secret" ] ; then
    openssl rand --base64 42 > /etc/postfix/postsrsd.secret
  fi
  postsrsd ${postsrs}
fi
/usr/sbin/postfix start
#wait $(cat /var/spool/postfix/pid/master.pid) $(cat /run/opendkim.pid)
sleep 10
if [ -x /usr/local/bin/postfix_exporter ]; then
  if [ -e /var/log/mail.log ]; then
    /usr/local/bin/postfix_exporter --web.listen-address ":9117" --collector file --file.log /var/log/mail.log &
  fi
fi
while [ -e /var/spool/postfix/pid/master.pid ] && [ -e /run/opendkim.pid ]; do
  for i in $(seq 1 100); do
    if [ ! -d /proc/$(tr -d " \t" < /var/spool/postfix/pid/master.pid) ]; then
      exit 1
    fi
    if [ ! -d /proc/$(tr -d " \t" < /run/opendkim.pid) ]; then
      exit 1
    fi
    sleep 10
  done
  if [ -e "$TLS_CERT" ]; then
    TLS_NEW=$(sha1sum $TLS_CERT)
    if [ "$TLS" != "$TLS_NEW" ]; then
      /usr/sbin/postfix reload
      TLS="$TLS_NEW"
    fi
  fi
done
exit 0
